#Shell Sink
#See http://shell-sink.blogspot.com/2008/12/installing-shellsink-client-application.html for installation instructions.
shopt -s histappend
export SHELL_SINK_COMMAND=shellsink-client
export SHELL_SINK_ID=your-hex-id
PROMPT_COMMAND="history -a;$SHELL_SINK_COMMAND"
export SHELL_SINK_TAGS=colon:delimited:list:of:tags
